<?php
/*
* Template Name: Template for Single portfolio
* Template Post Type: post
*/
?>
<?php get_header(); ?>
<?php


$post_id = get_queried_object_id();
$post = get_post($post_id);

?>
<div class="bread">
  <div class="contain">
    <div class="bread-w">
      <?php the_breadcrumb(); ?>
    </div>
  </div>
</div><!--bread-->
<div class="single-portfolio-content content">
  <div class="contain">
    <h1><?php echo get_field('status'); ?></h1>
    <div class="single-portfolio-title">
      <?php the_title(); ?>
    </div>
    <div class="single-overview">
      <div class="like-h3">      
        <?php echo get_field('portfolio_overview_title'); ?>
      </div>
      <div class="single-overview-desc">
        <?php echo get_field('portfolio_overview_desc'); ?>
      </div>
    </div><!--single-overview-->
  </div><!--contain-->
</div><!--single-portfolio-content-->
<div class="summary-block">
  <div class="contain">
    <div class="summary-txts-top">        
      <div class="like-h3"><?php echo get_field('summary_title'); ?></div>
      <div class="donut-date date-top"><?php echo get_field('geographic_allocation_date'); ?></div>
    </div><!--summary-txts-top-->
  </div>
  <div class="contain contain-summary">
    <table class="hide-768">
      <thead>
        <tr>
          <td>Investment Amount</td>
          <td>
            <span class="td-info">
              <span class="td-info-txt">Performance Fee</span>              
              <span class="td-tooltip">
                Performance fee is charged  from the amount of positive return on your investment generated by our portfolio managgers.
              </span>
            </span>            
          </td>
          <td class="td-green">
            <span class="td-info">
             <span class="td-info-txt">Subscription fee</span>
             <span class="td-tooltip">
              Subscription fee is chared for subscription to shares of any share class. eInvestment subscription fee is 0%.
            </span>
          </span>
        </td>
        <td class="td-green">
          <span class="td-info">

            <span class="td-info-txt">Management fee</span>
            <span class="td-tooltip">
              Management fee is charged for managing investor’s funds without regard to returns. eInvestment management fee is 0%.
            </span>
          </span>
        </td>        
        <td class="td-green">Ongoing fees</td>
        <td>Redemption fee</td>
        <td>Share class</td>
      </tr>          
    </thead>
    <tbody>
      <tr>
        <td><span class="td-eur">€ </span><?php echo get_field('investment_amount_1'); ?></td>
        <td class="td-perc"><?php echo get_field('performance_fee_1'); ?></td>
        <td class="td-big" colspan="3" rowspan="3"><?php echo get_field('subscription_management_ongoing_fees'); ?></td>
        <td class="td-perc td-perc-3" rowspan="3"><span class="r-fee"><?php echo get_field('redemption_fee'); ?></span></td>            
        <td class="td-lett"><?php echo get_field('share_class_1'); ?></td>
      </tr>
      <tr>
        <td><span class="td-eur">€ </span><?php echo get_field('investment_amount_2'); ?></td>
        <td class="td-perc"><?php echo get_field('performance_fee_2'); ?></td>
        <td class="td-lett"><?php echo get_field('share_class_2'); ?></td>            
      </tr>
      <tr>
        <td><span class="td-eur">€ </span><?php echo get_field('investment_amount_3'); ?></td>
        <td class="td-perc"><?php echo get_field('performance_fee_3'); ?></td>
        <td class="td-lett"><?php echo get_field('share_class_3'); ?></td>            
      </tr>
    </tbody>
  </table>

  <div class="td-show-768 summary-block-tables-768">
    <table>
      <thead>
        <tr>
          <td>Investment Amount</td>
          <td><span class="td-eur">€ </span><?php echo get_field('investment_amount_1'); ?></td>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <span class="td-info">

              <span class="td-info-txt">Performance Fee</span>
              <span class="td-tooltip">
                Performance fee is charged  from the amount of positive return on your investment generated by our portfolio managgers.
              </span>
            </span>
          </td>
          <td class="td-perc"><?php echo get_field('performance_fee_1'); ?></td>
        </tr>
        <tr>
          <td class="td-green">
            <span class="td-info">

              <span class="td-info-txt">Subscription fee</span>
              <span class="td-tooltip">
                Subscription fee is chared for subscription to shares of any share class. eInvestment subscription fee is 0%.
              </span>
            </span>
          </td>      
          <td class="td-big" rowspan="3"><?php echo get_field('subscription_management_ongoing_fees'); ?></td>
        </tr>
        <tr>
          <td class="td-green">
            <span class="td-info">

              <span class="td-info-txt">Management fee</span>
              <span class="td-tooltip">
                Management fee is charged for managing investor’s funds without regard to returns. eInvestment management fee is 0%.
              </span>
            </span>
          </td>                  
        </tr>
        <tr>
          <td class="td-green">Ongoing fees</td>
        </tr>
        <tr>
          <td>Redemption fee</td>
          <td class="td-perc"><span class="r-fee"><?php echo get_field('redemption_fee'); ?></span></td>                      
        </tr>
        <tr>
          <td>Share class</td>
          <td class="td-lett"><?php echo get_field('share_class_1'); ?></td>
        </tr>
      </tbody>
    </table>

    <table>
      <thead>
        <tr>
          <td>Investment Amount</td>
          <td><span class="td-eur">€ </span><?php echo get_field('investment_amount_2'); ?></td>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <span class="td-info">

              <span class="td-info-txt">Performance Fee</span>
              <span class="td-tooltip">
                Performance fee is charged  from the amount of positive return on your investment generated by our portfolio managgers.
              </span>
            </span>
          </td>
          <td class="td-perc"><?php echo get_field('performance_fee_2'); ?></td>
        </tr>
        <tr>
          <td class="td-green">
            <span class="td-info">

              <span class="td-info-txt">Subscription fee</span>
              <span class="td-tooltip">
                Subscription fee is chared for subscription to shares of any share class. eInvestment subscription fee is 0%.
              </span>
            </span>
          </td>      
          <td class="td-big" rowspan="3"><?php echo get_field('subscription_management_ongoing_fees'); ?></td>
        </tr>
        <tr>
          <td class="td-green">
            <span class="td-info">

              <span class="td-info-txt">Management fee</span>
              <span class="td-tooltip">
                Management fee is charged for managing investor’s funds without regard to returns. eInvestment management fee is 0%.
              </span>
            </span>
          </td>                  
        </tr>
        <tr>
          <td class="td-green">Ongoing fees</td>
        </tr>
        <tr>
          <td>Redemption fee</td>
          <td class="td-perc"><span class="r-fee"><?php echo get_field('redemption_fee'); ?></span></td>                      
        </tr>
        <tr>
          <td>Share class</td>
          <td class="td-lett"><?php echo get_field('share_class_2'); ?></td>
        </tr>
      </tbody>
    </table>

    <table>
      <thead>
        <tr>
          <td>Investment Amount</td>
          <td><span class="td-eur">€ </span><?php echo get_field('investment_amount_3'); ?></td>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <span class="td-info">

              <span class="td-info-txt">Performance Fee</span>
              <span class="td-tooltip">
                Performance fee is charged  from the amount of positive return on your investment generated by our portfolio managgers.
              </span>
            </span>
          </td>
          <td class="td-perc"><?php echo get_field('performance_fee_3'); ?></td>
        </tr>
        <tr>
          <td class="td-green">
            <span class="td-info">

              <span class="td-info-txt">Subscription fee</span>
              <span class="td-tooltip">
                Subscription fee is chared for subscription to shares of any share class. eInvestment subscription fee is 0%.
              </span>
            </span>
          </td>      
          <td class="td-big" rowspan="3"><?php echo get_field('subscription_management_ongoing_fees'); ?></td>
        </tr>
        <tr>
          <td class="td-green">
            <span class="td-info">

              <span class="td-info-txt">Management fee</span>
              <span class="td-tooltip">
                Management fee is charged for managing investor’s funds without regard to returns. eInvestment management fee is 0%.
              </span>
            </span>
          </td>                  
        </tr>
        <tr>
          <td class="td-green">Ongoing fees</td>
        </tr>
        <tr>
          <td>Redemption fee</td>
          <td class="td-perc"><span class="r-fee"><?php echo get_field('redemption_fee'); ?></span></td>                      
        </tr>
        <tr>
          <td>Share class</td>
          <td class="td-lett"><?php echo get_field('share_class_3'); ?></td>
        </tr>
      </tbody>
    </table>
  </div><!--td-show-768 summary-block-tables-768-->
</div><!--contain-->

</div><!--summary-block-->

<div class="bonut-block">
  <div class="contain">
    <div class="donut-wrap">
      <div class="donut-col donut-left">
        <div class="donut-title"><?php echo get_field('geographic_allocation_title'); ?></div>
        <div class="donut-date"><?php echo get_field('geographic_allocation_date'); ?></div>


        <div class="donut-flex">
          <div class="donut-donut">
            <div id="donut-chart-1"></div>
          </div>    
          <ul class="donut-list">


            <?php if( get_field('geographic_allocation_country_1') ): ?>
              <li>
                <span class="donut-dot" style="background-color: <?php echo get_field('geographic_allocation_color_1'); ?>"></span>
                <span class="colr">
                  <span class="donut-num"><?php echo get_field('geographic_allocation_percent_1'); ?></span>
                  <span class="donut-perc">%</span>
                </span>
                <span class="dunut-text"><?php echo get_field('geographic_allocation_country_1'); ?></span>
              </li>
            <?php endif; ?>

            <?php if( get_field('geographic_allocation_country_2') ): ?>
              <li>
                <span class="donut-dot" style="background-color: <?php echo get_field('geographic_allocation_color_2'); ?>"></span>
                <span class="colr">
                  <span class="donut-num"><?php echo get_field('geographic_allocation_percent_2'); ?></span>
                  <span class="donut-perc">%</span>
                </span>
                <span class="dunut-text"><?php echo get_field('geographic_allocation_country_2'); ?></span>
              </li>
            <?php endif; ?>

            <?php if( get_field('geographic_allocation_country_3') ): ?>
              <li>
                <span class="donut-dot" style="background-color: <?php echo get_field('geographic_allocation_color_3'); ?>"></span>
                <span class="colr">
                  <span class="donut-num"><?php echo get_field('geographic_allocation_percent_3'); ?></span>
                  <span class="donut-perc">%</span>
                </span>
                <span class="dunut-text"><?php echo get_field('geographic_allocation_country_3'); ?></span>
              </li>
            <?php endif; ?>

            <?php if( get_field('geographic_allocation_country_4') ): ?>
              <li>
                <span class="donut-dot" style="background-color: <?php echo get_field('geographic_allocation_color_4'); ?>"></span>
                <span class="colr">
                  <span class="donut-num"><?php echo get_field('geographic_allocation_percent_4'); ?></span>
                  <span class="donut-perc">%</span>
                </span>
                <span class="dunut-text"><?php echo get_field('geographic_allocation_country_4'); ?></span>
              </li>
            <?php endif; ?>

            <?php if( get_field('geographic_allocation_country_5') ): ?>
              <li>
                <span class="donut-dot" style="background-color: <?php echo get_field('geographic_allocation_color_5'); ?>"></span>
                <span class="colr">
                  <span class="donut-num"><?php echo get_field('geographic_allocation_percent_5'); ?></span>
                  <span class="donut-perc">%</span>
                </span>
                <span class="dunut-text"><?php echo get_field('geographic_allocation_country_5'); ?></span>
              </li>
            <?php endif; ?>

            <?php if( get_field('geographic_allocation_country_6') ): ?>
              <li>
                <span class="donut-dot" style="background-color: <?php echo get_field('geographic_allocation_color_6'); ?>"></span>
                <span class="colr">
                  <span class="donut-num"><?php echo get_field('geographic_allocation_percent_6'); ?></span>
                  <span class="donut-perc">%</span>
                </span>
                <span class="dunut-text"><?php echo get_field('geographic_allocation_country_6'); ?></span>
              </li>
            <?php endif; ?>

            <?php if( get_field('geographic_allocation_country_7') ): ?>
              <li>
                <span class="donut-dot" style="background-color: <?php echo get_field('geographic_allocation_color_7'); ?>"></span>
                <span class="colr">
                  <span class="donut-num"><?php echo get_field('geographic_allocation_percent_7'); ?></span>
                  <span class="donut-perc">%</span>
                </span>
                <span class="dunut-text"><?php echo get_field('geographic_allocation_country_7'); ?></span>
              </li>
            <?php endif; ?>

            <?php if( get_field('geographic_allocation_country_8') ): ?>
              <li>
                <span class="donut-dot" style="background-color: <?php echo get_field('geographic_allocation_color_8'); ?>"></span>
                <span class="colr">
                  <span class="donut-num"><?php echo get_field('geographic_allocation_percent_8'); ?></span>
                  <span class="donut-perc">%</span>
                </span>
                <span class="dunut-text"><?php echo get_field('geographic_allocation_country_8'); ?></span>
              </li>
            <?php endif; ?>

            <?php if( get_field('geographic_allocation_country_9') ): ?>
              <li>
                <span class="donut-dot" style="background-color: <?php echo get_field('geographic_allocation_color_9'); ?>"></span>
                <span class="colr">
                  <span class="donut-num"><?php echo get_field('geographic_allocation_percent_9'); ?></span>
                  <span class="donut-perc">%</span>
                </span>
                <span class="dunut-text"><?php echo get_field('geographic_allocation_country_9'); ?></span>
              </li>
            <?php endif; ?>

            <?php if( get_field('geographic_allocation_country_10') ): ?>
              <li>
                <span class="donut-dot" style="background-color: <?php echo get_field('geographic_allocation_color_10'); ?>"></span>
                <span class="colr">
                  <span class="donut-num"><?php echo get_field('geographic_allocation_percent_10'); ?></span>
                  <span class="donut-perc">%</span>
                </span>
                <span class="dunut-text"><?php echo get_field('geographic_allocation_country_10'); ?></span>
              </li>
            <?php endif; ?>

          </ul>
        </div><!--donut-flex-->

      </div><!--donut-left-->


      <div class="donut-col donut-right">
        <div class="donut-title"><?php echo get_field('sector_breakdown_title'); ?></div>
        <div class="donut-date"><?php echo get_field('geographic_allocation_date'); ?></div>
        <div class="donut-flex">
          <div class="donut-donut">
            <div id="donut-chart-2"></div>
          </div>    
          <ul class="donut-list">
            <?php if( get_field('sector_breakdown_name_1') ): ?>
              <li>
                <span class="donut-dot" style="background-color: <?php echo get_field('sector_breakdown_color_1'); ?>"></span>
                <span class="colr">
                  <span class="donut-num"><?php echo get_field('sector_breakdown_percent_1'); ?></span>
                  <span class="donut-perc">%</span>
                </span>
                <span class="dunut-text"><?php echo get_field('sector_breakdown_name_1'); ?></span>
              </li>
            <?php endif; ?>

            <?php if( get_field('sector_breakdown_name_2') ): ?>
              <li>
                <span class="donut-dot" style="background-color: <?php echo get_field('sector_breakdown_color_2'); ?>"></span>
                <span class="colr">
                  <span class="donut-num"><?php echo get_field('sector_breakdown_percent_2'); ?></span>
                  <span class="donut-perc">%</span>
                </span>
                <span class="dunut-text"><?php echo get_field('sector_breakdown_name_2'); ?></span>
              </li>
            <?php endif; ?>

            <?php if( get_field('sector_breakdown_name_3') ): ?>
              <li>
                <span class="donut-dot" style="background-color: <?php echo get_field('sector_breakdown_color_3'); ?>"></span>
                <span class="colr">
                  <span class="donut-num"><?php echo get_field('sector_breakdown_percent_3'); ?></span>
                  <span class="donut-perc">%</span>
                </span>
                <span class="dunut-text"><?php echo get_field('sector_breakdown_name_3'); ?></span>
              </li>
            <?php endif; ?>

            <?php if( get_field('sector_breakdown_name_4') ): ?>
              <li>
                <span class="donut-dot" style="background-color: <?php echo get_field('sector_breakdown_color_4'); ?>"></span>
                <span class="colr">
                  <span class="donut-num"><?php echo get_field('sector_breakdown_percent_4'); ?></span>
                  <span class="donut-perc">%</span>
                </span>
                <span class="dunut-text"><?php echo get_field('sector_breakdown_name_4'); ?></span>
              </li>
            <?php endif; ?>

            <?php if( get_field('sector_breakdown_name_5') ): ?>
              <li>
                <span class="donut-dot" style="background-color: <?php echo get_field('sector_breakdown_color_5'); ?>"></span>
                <span class="colr">
                  <span class="donut-num"><?php echo get_field('sector_breakdown_percent_5'); ?></span>
                  <span class="donut-perc">%</span>
                </span>
                <span class="dunut-text"><?php echo get_field('sector_breakdown_name_5'); ?></span>
              </li>
            <?php endif; ?>

            <?php if( get_field('sector_breakdown_name_6') ): ?>
              <li>
                <span class="donut-dot" style="background-color: <?php echo get_field('sector_breakdown_color_6'); ?>"></span>
                <span class="colr">
                  <span class="donut-num"><?php echo get_field('sector_breakdown_percent_6'); ?></span>
                  <span class="donut-perc">%</span>
                </span>
                <span class="dunut-text"><?php echo get_field('sector_breakdown_name_6'); ?></span>
              </li>
            <?php endif; ?>

            <?php if( get_field('sector_breakdown_name_7') ): ?>
              <li>
                <span class="donut-dot" style="background-color: <?php echo get_field('sector_breakdown_color_7'); ?>"></span>
                <span class="colr">
                  <span class="donut-num"><?php echo get_field('sector_breakdown_percent_7'); ?></span>
                  <span class="donut-perc">%</span>
                </span>
                <span class="dunut-text"><?php echo get_field('sector_breakdown_name_7'); ?></span>
              </li>
            <?php endif; ?>

            <?php if( get_field('sector_breakdown_name_8') ): ?>
              <li>
                <span class="donut-dot" style="background-color: <?php echo get_field('sector_breakdown_color_8'); ?>"></span>
                <span class="colr">
                  <span class="donut-num"><?php echo get_field('sector_breakdown_percent_8'); ?></span>
                  <span class="donut-perc">%</span>
                </span>
                <span class="dunut-text"><?php echo get_field('sector_breakdown_name_8'); ?></span>
              </li>
            <?php endif; ?>

            <?php if( get_field('sector_breakdown_name_9') ): ?>
              <li>
                <span class="donut-dot" style="background-color: <?php echo get_field('sector_breakdown_color_9'); ?>"></span>
                <span class="colr">
                  <span class="donut-num"><?php echo get_field('sector_breakdown_percent_9'); ?></span>
                  <span class="donut-perc">%</span>
                </span>
                <span class="dunut-text"><?php echo get_field('sector_breakdown_name_9'); ?></span>
              </li>
            <?php endif; ?>

            <?php if( get_field('sector_breakdown_name_10') ): ?>
              <li>
                <span class="donut-dot" style="background-color: <?php echo get_field('sector_breakdown_color_10'); ?>"></span>
                <span class="colr">
                  <span class="donut-num"><?php echo get_field('sector_breakdown_percent_10'); ?></span>
                  <span class="donut-perc">%</span>
                </span>
                <span class="dunut-text"><?php echo get_field('sector_breakdown_name_10'); ?></span>
              </li>
            <?php endif; ?>

          </ul>
        </div><!--donut-flex-->
      </div><!--donut-right-->
    </div><!--donut-wrap-->
  </div><!--contain-->
</div><!--bonut-block-->
<div class="allocation-highlights">
  <div class="contain">
    <div class="allocation-highlights-w">
      <div class="allocation-highlights-col">
        <div class="donut-title"><?php echo get_field('allocation_by_currency'); ?></div>
        <div class="donut-date"><?php echo get_field('geographic_allocation_date'); ?></div>

        <div class="allocation-highlights-block">

          <?php if( get_field('currency_1') ): ?>
            <div class="allocation-highlights-row">
              <div class="allocation-highlights-col-1">
                <?php echo get_field('currency_1'); ?>
                <div class="allocation-highlights-perc allocation-highlights-perc-hide"><span><?php echo get_field('scale_percent_1'); ?></span></div>
              </div>
              <div class="allocation-highlights-col-2 allocation-highlights-col-progress">
                <div class="allocation-highlights-perc"><span><?php echo get_field('scale_percent_1'); ?></span></div>
                <div class="allocation-highlights-progress">
                  <div class="allocation-highlights-progress-full"></div>
                </div><!--allocation-highlights-progress-->
              </div>
            </div><!--allocation-highlights-row-->
          <?php endif; ?>

          <?php if( get_field('currency_2') ): ?>
            <div class="allocation-highlights-row">
              <div class="allocation-highlights-col-1">
                <?php echo get_field('currency_2'); ?>
                <div class="allocation-highlights-perc allocation-highlights-perc-hide"><span><?php echo get_field('scale_percent_2'); ?></span></div>
              </div>
              <div class="allocation-highlights-col-2 allocation-highlights-col-progress">
                <div class="allocation-highlights-perc"><span><?php echo get_field('scale_percent_2'); ?></span></div>
                <div class="allocation-highlights-progress">
                  <div class="allocation-highlights-progress-full"></div>
                </div><!--allocation-highlights-progress-->
              </div>
            </div><!--allocation-highlights-row-->
          <?php endif; ?>

          <?php if( get_field('currency_3') ): ?>
            <div class="allocation-highlights-row">
              <div class="allocation-highlights-col-1">
                <?php echo get_field('currency_3'); ?>
                <div class="allocation-highlights-perc allocation-highlights-perc-hide"><span><?php echo get_field('scale_percent_3'); ?></span></div>
              </div>
              <div class="allocation-highlights-col-2 allocation-highlights-col-progress">
                <div class="allocation-highlights-perc"><span><?php echo get_field('scale_percent_3'); ?></span></div>
                <div class="allocation-highlights-progress">
                  <div class="allocation-highlights-progress-full"></div>
                </div><!--allocation-highlights-progress-->
              </div>
            </div><!--allocation-highlights-row-->
          <?php endif; ?>

          <?php if( get_field('currency_4') ): ?>
            <div class="allocation-highlights-row">
              <div class="allocation-highlights-col-1">
                <?php echo get_field('currency_4'); ?>
                <div class="allocation-highlights-perc allocation-highlights-perc-hide"><span><?php echo get_field('scale_percent_4'); ?></span></div>
              </div>
              <div class="allocation-highlights-col-2 allocation-highlights-col-progress">
                <div class="allocation-highlights-perc"><span><?php echo get_field('scale_percent_4'); ?></span></div>
                <div class="allocation-highlights-progress">
                  <div class="allocation-highlights-progress-full"></div>
                </div><!--allocation-highlights-progress-->
              </div>
            </div><!--allocation-highlights-row-->
          <?php endif; ?>

          <?php if( get_field('currency_5') ): ?>
            <div class="allocation-highlights-row">
              <div class="allocation-highlights-col-1">
                <?php echo get_field('currency_5'); ?>
                <div class="allocation-highlights-perc allocation-highlights-perc-hide"><span><?php echo get_field('scale_percent_5'); ?></span></div>
              </div>
              <div class="allocation-highlights-col-2 allocation-highlights-col-progress">
                <div class="allocation-highlights-perc"><span><?php echo get_field('scale_percent_5'); ?></span></div>
                <div class="allocation-highlights-progress">
                  <div class="allocation-highlights-progress-full"></div>
                </div><!--allocation-highlights-progress-->
              </div>
            </div><!--allocation-highlights-row-->
          <?php endif; ?>

          <?php if( get_field('currency_6') ): ?>
            <div class="allocation-highlights-row">
              <div class="allocation-highlights-col-1">
                <?php echo get_field('currency_6'); ?>
                <div class="allocation-highlights-perc allocation-highlights-perc-hide"><span><?php echo get_field('scale_percent_6'); ?></span></div>
              </div>
              <div class="allocation-highlights-col-2 allocation-highlights-col-progress">
                <div class="allocation-highlights-perc"><span><?php echo get_field('scale_percent_6'); ?></span></div>
                <div class="allocation-highlights-progress">
                  <div class="allocation-highlights-progress-full"></div>
                </div><!--allocation-highlights-progress-->
              </div>
            </div><!--allocation-highlights-row-->
          <?php endif; ?>

        </div><!--allocation-highlights-block-->
      </div><!--allocation-highlights-col-->

      <div class="allocation-highlights-col">
        <div class="donut-title"><?php echo get_field('portfolio_highlights'); ?></div>
        <div class="donut-date"><?php echo get_field('geographic_allocation_date'); ?></div>

        <div class="allocation-highlights-block allocation-highlights-block-2">

          <?php if( get_field('highlight_1') ): ?>
            <div class="allocation-highlights-row">
              <div class="allocation-highlights-col-1">
                <?php echo get_field('highlight_1'); ?>
              </div>
              <div class="allocation-highlights-col-2">
                <div class="allocation-highlights-perc-2 big-green"><span><?php echo get_field('highlight_data_1'); ?></span></div>              
              </div>
            </div><!--allocation-highlights-row-->
          <?php endif; ?>

          <?php if( get_field('highlight_2') ): ?>
            <div class="allocation-highlights-row">
              <div class="allocation-highlights-col-1">
                <?php echo get_field('highlight_2'); ?>
              </div>
              <div class="allocation-highlights-col-2">
                <div class="allocation-highlights-perc-2"><span><?php echo get_field('highlight_data_2'); ?></span></div>              
              </div>
            </div><!--allocation-highlights-row-->
          <?php endif; ?>

          <?php if( get_field('highlight_3') ): ?>
            <div class="allocation-highlights-row">
              <div class="allocation-highlights-col-1">
                <?php echo get_field('highlight_3'); ?>
              </div>
              <div class="allocation-highlights-col-2">
                <div class="allocation-highlights-perc-2"><span><?php echo get_field('highlight_data_3'); ?></span></div>              
              </div>
            </div><!--allocation-highlights-row-->
          <?php endif; ?>


          <?php if( get_field('highlight_4') ): ?>
            <div class="allocation-highlights-row">
              <div class="allocation-highlights-col-1">
                <?php echo get_field('highlight_4'); ?>
              </div>
              <div class="allocation-highlights-col-2">
                <div class="allocation-highlights-perc-2"><span><?php echo get_field('highlight_data_4'); ?></span></div>              
              </div>
            </div><!--allocation-highlights-row-->
          <?php endif; ?>

          <?php if( get_field('highlight_5') ): ?>
            <div class="allocation-highlights-row">
              <div class="allocation-highlights-col-1">
                <?php echo get_field('highlight_5'); ?>
              </div>
              <div class="allocation-highlights-col-2">
                <div class="allocation-highlights-perc-2 fs-16"><span><?php echo get_field('highlight_data_5'); ?></span></div>              
              </div>
            </div><!--allocation-highlights-row-->
          <?php endif; ?>

          <?php if( get_field('highlight_6') ): ?>
            <div class="allocation-highlights-row">
              <div class="allocation-highlights-col-1">
                <?php echo get_field('highlight_6'); ?>
              </div>
              <div class="allocation-highlights-col-2">
                <div class="allocation-highlights-perc-2 fs-16"><span><?php echo get_field('highlight_data_6'); ?></span></div>
              </div>
            </div><!--allocation-highlights-row-->
          <?php endif; ?>

        </div><!--allocation-highlights-block-->
      </div><!--allocation-highlights-col-->
    </div><!--allocation-highlights-w-->
  </div><!--contain-->
</div><!--allocation-highlights-->

<div class="distribution-reports">
  <div class="contain">
    <div class="like-h3"><?php echo get_field('interest_distribution_reports_title'); ?></div>
    <div class="distribution-reports-table-wrap">
      <ul class="tabs-control">
        <li class="tabs_control_item active">
          <a href="#" class="tabs_control_link">
            Recent             
          </a>
        </li>
        <li class="tabs_control_item">
          <a href="#" class="tabs_control_link">
            Scheduled              
          </a>
        </li>
      </ul><!--tabs-control-->
      <ul class="tabs_content">
        <li class="tabs_content_item active">                 

          <table class="hide-768">
            <thead>
              <tr>
                <td>Investment Period</td>
                <td>Execution date</td>
                <td>Reinvest date</td>
                <td>Payable date</td>
                <td>Interest rate </td>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>
                  <?php
                  $arr_per_1 = get_field('interest_distribution_reports_row_1');
                  echo $arr_per_1['investment_period']
                  ?>
                </td>
                <td><?php echo $arr_per_1['execution_date'] ?></td>
                <td><?php echo $arr_per_1['reinvest_date'] ?></td>
                <td><?php echo $arr_per_1['payable_date'] ?></td>
                <td class="td-percents"><?php echo $arr_per_1['interest_rate'] ?></td>
              </tr>

              <tr>
                <td>
                  <?php
                  $arr_per_2 = get_field('interest_distribution_reports_row_2');
                  echo $arr_per_2['investment_period']
                  ?>
                </td>
                <td><?php echo $arr_per_2['execution_date'] ?></td>
                <td><?php echo $arr_per_2['reinvest_date'] ?></td>
                <td><?php echo $arr_per_2['payable_date'] ?></td>
                <td class="td-percents"><?php echo $arr_per_2['interest_rate'] ?></td>
              </tr>

              <tr>
                <td>
                  <?php
                  $arr_per_3 = get_field('interest_distribution_reports_row_3');
                  echo $arr_per_3['investment_period']
                  ?>
                </td>
                <td><?php echo $arr_per_3['execution_date'] ?></td>
                <td><?php echo $arr_per_3['reinvest_date'] ?></td>
                <td><?php echo $arr_per_3['payable_date'] ?></td>
                <td class="td-percents"><?php echo $arr_per_3['interest_rate'] ?></td>
              </tr>

              <tr>
                <td>
                  <?php
                  $arr_per_4 = get_field('interest_distribution_reports_row_4');
                  echo $arr_per_4['investment_period']
                  ?>
                </td>
                <td><?php echo $arr_per_4['execution_date'] ?></td>
                <td><?php echo $arr_per_4['reinvest_date'] ?></td>
                <td><?php echo $arr_per_4['payable_date'] ?></td>
                <td class="td-percents"><?php echo $arr_per_4['interest_rate'] ?></td>
              </tr>

              <tr>
                <td>
                  <?php
                  $arr_per_5 = get_field('interest_distribution_reports_row_5');
                  echo $arr_per_5['investment_period']
                  ?>
                </td>
                <td><?php echo $arr_per_5['execution_date'] ?></td>
                <td><?php echo $arr_per_5['reinvest_date'] ?></td>
                <td><?php echo $arr_per_5['payable_date'] ?></td>
                <td class="td-percents"><?php echo $arr_per_5['interest_rate'] ?></td>
              </tr>

            </tbody>
          </table> 

          
          <div class="distribution-reports-tables-768 td-show-768">

            <table>
              <tr>
                <td>Investment Period</td>
                <td><?php echo $arr_per_1['investment_period'] ?></td>
              </tr>
              <tr>
                <td>Execution date</td>                
                <td><?php echo $arr_per_1['execution_date'] ?></td>                
              </tr>
              <tr>
                <td>Reinvest date</td>
                <td><?php echo $arr_per_1['reinvest_date'] ?></td>                
              </tr>
              <tr>
                <td>Payable date</td>
                <td><?php echo $arr_per_1['payable_date'] ?></td>                
              </tr>
              <tr>
                <td>Interest rate </td>
                <td class="td-percents"><?php echo $arr_per_1['interest_rate'] ?></td>
              </tr>
              
            </table>

            <table>
              <tr>
                <td>Investment Period</td>
                <td><?php echo $arr_per_2['investment_period'] ?></td>
              </tr>
              <tr>
                <td>Execution date</td>                
                <td><?php echo $arr_per_2['execution_date'] ?></td>                
              </tr>
              <tr>
                <td>Reinvest date</td>
                <td><?php echo $arr_per_2['reinvest_date'] ?></td>                
              </tr>
              <tr>
                <td>Payable date</td>
                <td><?php echo $arr_per_2['payable_date'] ?></td>                
              </tr>
              <tr>
                <td>Interest rate </td>
                <td class="td-percents"><?php echo $arr_per_2['interest_rate'] ?></td>
              </tr>
              
            </table>

            <table>
              <tr>
                <td>Investment Period</td>
                <td><?php echo $arr_per_3['investment_period'] ?></td>
              </tr>
              <tr>
                <td>Execution date</td>                
                <td><?php echo $arr_per_3['execution_date'] ?></td>                
              </tr>
              <tr>
                <td>Reinvest date</td>
                <td><?php echo $arr_per_3['reinvest_date'] ?></td>                
              </tr>
              <tr>
                <td>Payable date</td>
                <td><?php echo $arr_per_3['payable_date'] ?></td>                
              </tr>
              <tr>
                <td>Interest rate </td>
                <td class="td-percents"><?php echo $arr_per_3['interest_rate'] ?></td>
              </tr>
              
            </table>

            <table>
              <tr>
                <td>Investment Period</td>
                <td><?php echo $arr_per_4['investment_period'] ?></td>
              </tr>
              <tr>
                <td>Execution date</td>                
                <td><?php echo $arr_per_4['execution_date'] ?></td>                
              </tr>
              <tr>
                <td>Reinvest date</td>
                <td><?php echo $arr_per_4['reinvest_date'] ?></td>                
              </tr>
              <tr>
                <td>Payable date</td>
                <td><?php echo $arr_per_4['payable_date'] ?></td>                
              </tr>
              <tr>
                <td>Interest rate </td>
                <td class="td-percents"><?php echo $arr_per_4['interest_rate'] ?></td>
              </tr>
              
            </table>

            <table>
              <tr>
                <td>Investment Period</td>
                <td><?php echo $arr_per_5['investment_period'] ?></td>
              </tr>
              <tr>
                <td>Execution date</td>                
                <td><?php echo $arr_per_5['execution_date'] ?></td>                
              </tr>
              <tr>
                <td>Reinvest date</td>
                <td><?php echo $arr_per_5['reinvest_date'] ?></td>                
              </tr>
              <tr>
                <td>Payable date</td>
                <td><?php echo $arr_per_5['payable_date'] ?></td>                
              </tr>
              <tr>
                <td>Interest rate </td>
                <td class="td-percents"><?php echo $arr_per_5['interest_rate'] ?></td>
              </tr>
              
            </table>

          </div><!--distribution-reports-tables-768-->

        </li>
        <li class="tabs_content_item"> 

          <table class="hide-768 distribution-reports-table-2">
            <thead>
              <tr>
                <td>Investment Period</td>
                <td>Execution date</td>
                <td>Reinvest date</td>
                <td>Payable date</td>                
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>
                  <?php
                  $arr_per_1 = get_field('interest_distribution_reports_row_1');
                  echo $arr_per_1['investment_period']
                  ?>
                </td>
                <td><?php echo $arr_per_1['execution_date'] ?></td>
                <td><?php echo $arr_per_1['reinvest_date'] ?></td>
                <td><?php echo $arr_per_1['payable_date'] ?></td>                
              </tr>

              <tr>
                <td>
                  <?php
                  $arr_per_2 = get_field('interest_distribution_reports_row_2');
                  echo $arr_per_2['investment_period']
                  ?>
                </td>
                <td><?php echo $arr_per_2['execution_date'] ?></td>
                <td><?php echo $arr_per_2['reinvest_date'] ?></td>
                <td><?php echo $arr_per_2['payable_date'] ?></td>                
              </tr>

              <tr>
                <td>
                  <?php
                  $arr_per_3 = get_field('interest_distribution_reports_row_3');
                  echo $arr_per_3['investment_period']
                  ?>
                </td>
                <td><?php echo $arr_per_3['execution_date'] ?></td>
                <td><?php echo $arr_per_3['reinvest_date'] ?></td>
                <td><?php echo $arr_per_3['payable_date'] ?></td>                
              </tr>

              <tr>
                <td>
                  <?php
                  $arr_per_4 = get_field('interest_distribution_reports_row_4');
                  echo $arr_per_4['investment_period']
                  ?>
                </td>
                <td><?php echo $arr_per_4['execution_date'] ?></td>
                <td><?php echo $arr_per_4['reinvest_date'] ?></td>
                <td><?php echo $arr_per_4['payable_date'] ?></td>                
              </tr>

              <tr>
                <td>
                  <?php
                  $arr_per_5 = get_field('interest_distribution_reports_row_5');
                  echo $arr_per_5['investment_period']
                  ?>
                </td>
                <td><?php echo $arr_per_5['execution_date'] ?></td>
                <td><?php echo $arr_per_5['reinvest_date'] ?></td>
                <td><?php echo $arr_per_5['payable_date'] ?></td>                
              </tr>

            </tbody>
          </table> 

          <div class="distribution-reports-tables-768 td-show-768">

            <table>
              <tr>
                <td>Investment Period</td>
                <td><?php echo $arr_per_1['investment_period'] ?></td>
              </tr>
              <tr>
                <td>Execution date</td>                
                <td><?php echo $arr_per_1['execution_date'] ?></td>                
              </tr>
              <tr>
                <td>Reinvest date</td>
                <td><?php echo $arr_per_1['reinvest_date'] ?></td>                
              </tr>
              <tr>
                <td>Payable date</td>
                <td><?php echo $arr_per_1['payable_date'] ?></td>                
              </tr>
              
            </table>

            <table>
              <tr>
                <td>Investment Period</td>
                <td><?php echo $arr_per_2['investment_period'] ?></td>
              </tr>
              <tr>
                <td>Execution date</td>                
                <td><?php echo $arr_per_2['execution_date'] ?></td>                
              </tr>
              <tr>
                <td>Reinvest date</td>
                <td><?php echo $arr_per_2['reinvest_date'] ?></td>                
              </tr>
              <tr>
                <td>Payable date</td>
                <td><?php echo $arr_per_2['payable_date'] ?></td>                
              </tr>
              
            </table>

            <table>
              <tr>
                <td>Investment Period</td>
                <td><?php echo $arr_per_3['investment_period'] ?></td>
              </tr>
              <tr>
                <td>Execution date</td>                
                <td><?php echo $arr_per_3['execution_date'] ?></td>                
              </tr>
              <tr>
                <td>Reinvest date</td>
                <td><?php echo $arr_per_3['reinvest_date'] ?></td>                
              </tr>
              <tr>
                <td>Payable date</td>
                <td><?php echo $arr_per_3['payable_date'] ?></td>                
              </tr>
              
            </table>

            <table>
              <tr>
                <td>Investment Period</td>
                <td><?php echo $arr_per_4['investment_period'] ?></td>
              </tr>
              <tr>
                <td>Execution date</td>                
                <td><?php echo $arr_per_4['execution_date'] ?></td>                
              </tr>
              <tr>
                <td>Reinvest date</td>
                <td><?php echo $arr_per_4['reinvest_date'] ?></td>                
              </tr>
              <tr>
                <td>Payable date</td>
                <td><?php echo $arr_per_4['payable_date'] ?></td>                
              </tr>
              
            </table>

            <table>
              <tr>
                <td>Investment Period</td>
                <td><?php echo $arr_per_5['investment_period'] ?></td>
              </tr>
              <tr>
                <td>Execution date</td>                
                <td><?php echo $arr_per_5['execution_date'] ?></td>                
              </tr>
              <tr>
                <td>Reinvest date</td>
                <td><?php echo $arr_per_5['reinvest_date'] ?></td>                
              </tr>
              <tr>
                <td>Payable date</td>
                <td><?php echo $arr_per_5['payable_date'] ?></td>                
              </tr>
              
            </table>

          </div><!--distribution-reports-tables-768-->

        </li><!--services-full-desc-item-->

      </ul><!--tabs-list-->
    </div><!--distribution-reports-table-wrap-->
  </div><!--contain-->
</div><!--distribution-reports-->

<div class="portfolio-managers">
  <div class="contain">
    <div class="like-h3"><?php echo get_field('portfolio_managers_title'); ?></div>
    <div class="managers-w">

      <?php if( get_field('portfolio_manager_1') ): ?>
        <div class="managers-item">
          <?php
          $prm_1 = get_field('portfolio_manager_1');
          ?>
          <div class="managers-img-w">
            <img src="<?php echo $prm_1['manager_img'] ?>" alt="manager-photo">
          </div><!--managers-img-w-->
          <div class="managers-txts">
            <div class="managers-txt-1"><?php echo $prm_1['manager_text_1']; ?></div>
            <div class="managers-txt-2"><?php echo $prm_1['manager_text_2']; ?></div>
            <div class="managers-txt-3"><?php echo $prm_1['manager_text_3']; ?></div>
          </div><!--managers-txts-->
        </div><!--managers-item-->
      <?php endif; ?>

      <?php if( get_field('portfolio_manager_2') ): ?>
        <div class="managers-item">
          <?php
          $prm_2 = get_field('portfolio_manager_2');
          ?>
          <div class="managers-img-w">
            <img src="<?php echo $prm_2['manager_img'] ?>" alt="manager-photo">
          </div><!--managers-img-w-->
          <div class="managers-txts">
            <div class="managers-txt-1"><?php echo $prm_2['manager_text_1']; ?></div>
            <div class="managers-txt-2"><?php echo $prm_2['manager_text_2']; ?></div>
            <div class="managers-txt-3"><?php echo $prm_2['manager_text_3']; ?></div>
          </div><!--managers-txts-->
        </div><!--managers-item-->
      <?php endif; ?>

      <?php if( get_field('portfolio_manager_3') ): ?>
        <div class="managers-item">
          <?php
          $prm_3 = get_field('portfolio_manager_3');
          ?>
          <div class="managers-img-w">
            <img src="<?php echo $prm_3['manager_img'] ?>" alt="manager-photo">
          </div><!--managers-img-w-->
          <div class="managers-txts">
            <div class="managers-txt-1"><?php echo $prm_3['manager_text_1']; ?></div>
            <div class="managers-txt-2"><?php echo $prm_3['manager_text_2']; ?></div>
            <div class="managers-txt-3"><?php echo $prm_3['manager_text_3']; ?></div>
          </div><!--managers-txts-->
        </div><!--managers-item-->
      <?php endif; ?>

    </div><!--managers-w-->
  </div>
</div><!--portfolio-managers-->

<div class="join-3-next-w">
  <div class="join join-3">
    <div class="contain">
      <?php
      $post = get_post(411);
      ?>
      <div class="join-w">
        <div class="join-l">
          <img
          src="<? bloginfo('template_url') ?>/img/join-phone@2x.png"
          alt="join-phone"
          srcset="<? bloginfo('template_url') ?>/img/join-phone.png 1x,
          <? bloginfo('template_url') ?>/img/join-phone@2x.png 2x"
          >
        </div>      
        <div class="join-r">
          <div class="join-txt-1">          
            <?php echo $post->post_title;?>
          </div> 
          <div class="join-txt-2 join-3-txt-2">
            <?php echo $post->post_content;?>
          </div>
          <div class="join-3-butt-wrap">
            <a href="<?php echo get_field('button_link'); ?>" class="butt"><?php echo get_field('button_text'); ?></a>
          </div><!--join-3-butt-wrap-->
        </div>
      </div>
    </div>
  </div><!--join-->
  <div class="next-portfolio">  
    <div class="portfolios-w-2">    
      <div class="portfolios-items-2">      

        <?php
        $i = 1;
        $post_id = get_queried_object_id();
        $post = get_post($post_id);

        $cats = query_posts(array('posts_per_page' => 100, 'cat' => 3));

        $other_post_arr = [];

        for ($c = 0; $c <= count($cats) - 1; $c++) {
          $other_post_arr[] = $cats[$c]->ID;
        }

        for ($s = 0; $s <= count($cats) - 1; $s++) {
          if ( $other_post_arr[$s] != $post->ID) {
            $other_post_clean =  $other_post_arr[$s].'<br>';
          }    
        }
        $post = get_post($other_post_clean);
        ?>
        <div class="portfolios-item-2">        
          <div class="contain contain-portfolios">
            <div class="like-h2">Next Portfolio</div>
            <div class="portfolios-item-w portfolios-item-w-3 wrap">              
              <div class="portfolios-item-l">
                <div class="portfolios-item-txt-1">                                 
                  <?php echo get_field('status'); ?>                                                
                </div>
                <div class="portfolios-item-txt-2">                
                  <?php the_title(); ?>
                </div>
                <div class="portfolios-item-txt-3">
                  <?php echo get_field('interest_distribution_frequency'); ?>                    
                </div>
                <div class="portfolios-item-txt-4">
                  <?php echo get_field('short_description'); ?>                    
                </div>                  
                <a href="<?php the_permalink(); ?>" class="butt-o hide-768">View details</a>
              </div><!--portfolios-item-l-->
              <div class="portfolios-item-r">
                <div class="graph graph-portfolios graph-portfolios-<?php echo $i ?>">
                  <div class="graph-txt-1"><?php echo get_field('latest_dividends_distributions_text'); ?></div>
                  <div class="graph-info">
                    <div class="graph-info-l">
                      <div class="graph-info-txts">
                        <span>Period</span>
                        <span>Interest Rate</span>
                      </div>
                      <span class="info-line"></span>
                    </div>
                    <div class="graph-info-r">
                      <div class="period period-1">
                        <span class="week"><?php echo get_field('period_1'); ?></span>
                        <span class="perc"><?php echo get_field('interest_rate_1'); ?></span>
                      </div>
                      <div class="period period-2">
                        <span class="week"><?php echo get_field('period_2'); ?></span>
                        <span class="perc"><?php echo get_field('interest_rate_2'); ?></span>
                      </div>
                      <div class="period period-3">
                        <span class="week"><?php echo get_field('period_3'); ?></span>
                        <span class="perc"><?php echo get_field('interest_rate_3'); ?></span>
                      </div>
                    </div>
                  </div><!--graph-info-->
                  <div class="chart">
                    <div class="chart-l">
                      <div class="chart-txt">Max</div>
                      <div class="chart-txt">Hi</div>
                      <div class="chart-txt">Med</div>
                      <div class="chart-txt">Lo</div>
                      <div class="chart-txt">Min</div>
                    </div>
                    <div class="chart-r">
                      <div class="lines">
                        <div class="line line-1"></div>
                        <div class="line line-2"></div>
                        <div class="line line-3"></div>
                      </div>
                      <div class="chart-cols">
                        <div class="chart-col-w chart-col-w-1">
                          <div class="chart-col chart-col-<?php echo $i ?>" data-height="<?php echo get_field('scale_height_1'); ?>px"></div>
                          <div class="chart-date"><?php echo get_field('scale_date_1'); ?></div>
                        </div><!--chart-col-w-->
                        <div class="chart-col-w chart-col-w-2">
                          <div class="chart-col chart-col-<?php echo $i ?>" data-height="<?php echo get_field('scale_height_2'); ?>px"></div>
                          <div class="chart-date"><?php echo get_field('scale_date_2'); ?></div>
                        </div><!--chart-col-w-->
                        <div class="chart-col-w chart-col-w-3">
                          <div class="chart-col chart-col-<?php echo $i ?>" data-height="<?php echo get_field('scale_height_3'); ?>px"></div>
                          <div class="chart-date"><?php echo get_field('scale_date_3'); ?></div>
                        </div><!--chart-col-w-->
                        <div class="chart-col-w chart-col-w-4">
                          <div class="chart-col chart-col-<?php echo $i ?>" data-height="<?php echo get_field('scale_height_4'); ?>px"></div>
                          <div class="chart-date"><?php echo get_field('scale_date_4'); ?></div>
                        </div><!--chart-col-w-->
                        <div class="chart-col-w chart-col-w-5">
                          <div class="chart-col chart-col-<?php echo $i ?>" data-height="<?php echo get_field('scale_height_5'); ?>px"></div>
                          <div class="chart-date"><?php echo get_field('scale_date_5'); ?></div>
                        </div><!--chart-col-w-->
                      </div><!--chart-cols-->
                    </div>
                  </div>
                </div><!--graph-->
                <div class="show-768 graph-butt-wrap">
                  <a href="<?php the_permalink(); ?>" class="butt-o">View details</a>
                </div>
              </div><!--portfolios-item-r-->              
            </div><!--portfolios-item-w-->
          </div><!--contain-->
        </div><!--portfolios-item-->

      </div><!--portfolios-items-->
    </div><!--portpholios-w--> 
  </div><!--next-portfolio-->
</div><!--join-3-next-w-->

<?php get_footer(); ?>
